# Generated by Django 4.2.5 on 2023-10-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='story',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='threads_app.story'),
        ),
    ]
