# Generated by Django 4.2.5 on 2023-10-07 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads_app', '0004_remove_userprofile_email_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 7, 19, 10, 16, 750951), null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_active',
            field=models.BooleanField(default=True, null=True, verbose_name='isActive'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_portfolio',
            field=models.URLField(blank=True, default='https://example.com/default-portfolio', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_profilepic',
            field=models.FilePathField(blank=True, default=None, match='.jpeg', null=True, path='media/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('fa30b429-9455-4e68-828a-9edfed982ca9'), editable=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='threads_app.story'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_content',
            field=models.TextField(),
        ),
    ]
