# Generated by Django 4.2.5 on 2023-10-08 09:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads_app', '0005_story_date_userprofile_user_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 9, 49, 14, 660365), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('5f3d1383-bc78-4bc8-a96b-c1a076ef1ba5'), editable=False),
        ),
    ]
