# Generated by Django 4.2.5 on 2023-10-09 05:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads_app', '0007_story_story_media_alter_story_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 9, 5, 28, 29, 657999), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('7da7c7c5-f3e2-4db4-a8d2-a45fd2272c26'), editable=False),
        ),
    ]
