# Generated by Django 4.2.5 on 2023-10-10 05:59

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('threads_app', '0008_alter_story_date_alter_userprofile_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 10, 5, 59, 51, 615872), null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_active',
            field=models.BooleanField(default=True, verbose_name='isActive'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_uuid',
            field=models.UUIDField(default=uuid.UUID('67d34e90-bc99-4a58-8691-da61006c753a'), editable=False),
        ),
    ]
